apiVersion: v1
kind: Service
metadata:
  name: hanko
  namespace: hanko
spec:
  selector:
    app: hanko
  ports:
    - port: 80
      targetPort: public
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: hanko-private
  namespace: hanko
spec:
  selector:
    app: hanko
  ports:
    - port: 80
      targetPort: private
      protocol: TCP
      name: http
