name: Authenticator Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working-directory: ./authenticator-backend
      run: go build -v ./...

    - name: Test
      working-directory: ./authenticator-backend
      run: go test -v ./...
